#### Vintage Pi TV configuration ####

# Log level, one of silent, error, warning, info, or debug
log_level = 'debug'

timezone = 'US/Eastern'  # From the

# Set to false to disable storing a toml DB file (relative paths relative to this config file)
videos_db_file = "videos-db.toml"
#videos_db_file = false

# Sould we provide visualizations for audio files?
enable_audio_visualization = true

# Ratings must be in order least restricted to most restricted, eg. G first, X last
ratings = [
    { rating = "G", description = "General" },  # First item will be the default
    { rating = "PG", description = "Parental Guidance"},
    { rating = "R", description = "Restricted" },
    { rating = "X", description = "Adult"}
]

# Margin of monitor in pixels, for overscan purposes
overscan_margin = false
# overscan_margin = { "left": 10, "top": 10, "right": 10, "bottom": 10 }

# Or disable ratings altogether
# atings = false

# Directories to search for videos in, wildcards accepted. This key is required.
search_dirs = [
    { path = "/media/VintagePiTV/videos", recurse = true},
    { path = "/media/VintagePiTV", ignore = true },
    "/media/*",
    # { path = "/media/*", recurse = true },
]

# Set valid file extensions to "defaults"
valid_file_extensions = "defaults"
# Or or provide a list of extensions (without the period)
# valid_file_extensions = [ "mp4", "mkv", "mov", "avi" ]

# MPV driver for audio (default is alsa) -- see https://mpv.io/manual/master/#audio-output-drivers
#audio_driver = 'alsa'

# MPV driver for video (default is drm) -- see https://mpv.io/manual/master/#video-output-drivers
#video_driver = 'drm'

# For advanced users only! Arguments to the mpv.MPV() constructor in python-mpv
# See https://github.com/jaseg/python-mpv for more details
# NOTE: mpv arguments should be translated to use underscores instead of hyfens
#extra_mpv_options = { alsa_device = "hw:0,0" }
