#### Vintage Pi TV configuration ####

# Log level, one of silent, error, warning, info, or debug
log_level = 'debug'

# Set to false to disable storing a toml DB file (relative paths relative to this config file)
videos_db_file = "videos-db.toml"
#videos_db_file = false

# Sould we provide visualizations for audio files?
enable_audio_visualization = true

# Ratings must be in order least restricted to most restricted, eg. G first, X last
ratings = [
    { rating = "G", description = "General" },  # First item will be the default
    { rating = "PG", description = "Parental Guidance"},
    { rating = "R", description = "Restricted" },
    { rating = "X", description = "Adult"}
]

# Margin of monitor in pixels, for overscan purposes
#overscan_margin = false
# overscan_margin = { "left": 10, "top": 10, "right": 10, "bottom": 10 }

# Or disable ratings altogether
# atings = false

# Directories to search for videos in, wildcards accepted. This key is required.
search_dirs = [
    { path = "/media/VintagePiTV/videos", recurse = true},
    { path = "/media/VintagePiTV", ignore = true },
    "/media/*",
    # { path = "/media/*", recurse = true },
]

# Set valid file extensions to "defaults"
valid_file_extensions = "defaults"
# Or or provide a list of extensions (without the period)
# valid_file_extensions = [ "mp4", "mkv", "mov", "avi" ]

### MPV options ###
[mpv_options]

# WARNING: For advanced users only! Arguments converted the mpv.MPV(...) constructor in python-mpv
# See https://github.com/jaseg/python-mpv and https://mpv.io/manual/stable/ for more details

### Defaults (uncomment to change)
#ao = "pipewire"      # audio output driver [https://mpv.io/manual/stable/#audio-output-drivers]
#vo = "gpu"           # video output driver [https://mpv.io/manual/stable/#video-output-drivers]
#hwdec = "auto-safe"
#profile = "sw-fast"
#gpu-context = "drm"
#fullscreen = true

### More relevant settings
#drm-connector = "TODO"  # Which monitor to use [https://mpv.io/manual/stable/#video-output-drivers-drm-connector]
                         # For options, run: $ mpv --drm-connector=help

#drm-mode = "1920x1080"  # DRM mode, set custom resolution here [https://mpv.io/manual/stable/#video-output-drivers-drm-mode]
                         # Use "preferred", "highest", or for more options, run: $ mpv --drm-mode=help
#alsa-device = "hw:0,0"
