name: Build Retro Pi TV

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref_type }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  POETRY_VERSION: 1.7.1
  BASE_IMAGE_URL: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2023-12-11/2023-12-11-raspios-bookworm-arm64-lite.img.xz

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build image
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        id: vars
        name: Set vars
        shell: bash
        run: |

          if [ "${GITHUB_REF_TYPE}" = 'tag' ]; then
            SUFFIX="${GITHUB_REF_NAME}"
            echo "short-version=${GITHUB_REF_NAME:1}" >> "${GITHUB_OUTPUT}"
          else
            SHORT_SHA=${GITHUB_SHA:0:8}
            SUFFIX="preview-${SHORT_SHA}"
            echo "short-sha=${SHORT_SHA}" >> "${GITHUB_OUTPUT}"
          fi
          echo "image-path=$(date +%Y-%m-%d)-raspios-bookworm-arm64-retro-pi-tv_${SUFFIX}.img" >> "${GITHUB_OUTPUT}"
      -
        name: Create Raspberry Pi OS image
        uses: dtcooper/rpi-image-modifier@v1
        id: image
        env:
          RUN_RETRO_PI_TV_BUILD_SCRIPT: "1"
        with:
          base-image-url: ${{ env.BASE_IMAGE_URL }}
          script-path : image/build.sh
          env-vars: RUN_RETRO_PI_TV_BUILD_SCRIPT,POETRY_VERSION,GITHUB_REF_NAME,GITHUB_REPOSITORY
          image-path: ${{ steps.vars.outputs.image-path }}
          compress-with-xz: true
          extra-xz-args: ${{ github.ref_type == 'tag' && '-9e' || '' }}  # Compress more for release
          cache: true
      -
        name: Remove old preview release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        if: github.ref_type != 'tag'
        with:
          delete_release: true
          tag_name: preview-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Prepare for release
        shell: bash
        run: |
          echo "${{ steps.image.outputs.image-sha256sum }}  ${{ steps.image.outputs.image-path }}" > "${{ steps.image.outputs.image-path }}.sha256sum"
          if [ "${GITHUB_REF_TYPE}" != 'tag' ]; then
            echo 'Waiting 15s for old release to delete'
            sleep 15s
          fi
      -
        name: Tag and upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.image.outputs.image-path }},${{ steps.image.outputs.image-path }}.sha256sum
          name: ${{ github.ref_type == 'tag' && format('Version {0}', steps.vars.outputs.short-version) || format('Preview Build {0}', steps.vars.outputs.short-sha) }}
          body: |-
            Retro Pi TV ${{ github.ref_type == 'tag' && format('Release {0}', steps.vars.outputs.short-version) || format('Preview Build {0}', steps.vars.outputs.short-sha) }}

            Image filename: ${{ steps.image.outputs.image-path }}
            SHA256SUM: ${{ steps.image.outputs.image-sha256sum }}

            ${{ github.ref_type != 'tag' &&  'This development preview build may not be safe; use it at your own risk.' || ''}}
          tag: ${{ github.ref_type == 'tag' && github.ref_name || 'preview-build' }}
          prerelease: ${{ github.ref_type != 'tag' }}
          token: ${{ secrets.GITHUB_TOKEN }}
