name: Build Retro Pi TV

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: true

env:
  POETRY_VERSION: 1.7.1
  BASE_IMAGE_URL: https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2023-12-11/2023-12-11-raspios-bookworm-arm64-lite.img.xz

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build image
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        id: vars
        name: Set vars
        shell: bash
        run: |
          echo "image-path=$(date +%Y-%m-%d)-raspios-bookworm-arm64-retro-pi-tv.img" >> "${GITHUB_OUTPUT}"
      -
        name: Create Raspberry Pi OS image
        uses: dtcooper/rpi-image-modifier@v1
        id: create-image
        with:
          base-image-url: ${{ env.BASE_IMAGE_URL }}
          image-path: ${{ steps.vars.outputs.image-path }}
          compress-with-xz: true
          cache: true
          env-vars: POETRY_VERSION,GITHUB_REF_NAME,GITHUB_REPOSITORY
          script: image/build.sh
      -
        name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-image
          path: ${{ steps.create-image.outputs.image-path }}
          if-no-files-found: error
          retention-days: 2
          compression-level: 0  # Already compressed with xz above
